apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: pythonAgendDNA
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonAgendDNA
  template:
    metadata:
      labels:
        app: pythonAgendDNA
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ['sh', '-c', 'echo The Pod is running && sleep 6']

